#define bzero           potatoes_bzero
#define cputs           potatoes_cputs
#define free            potatoes_free
#define get_hdsize      potatoes_get_hdsize
#define hd_read_sector  potatoes_hd_read_sector
#define hd_write_sector potatoes_hd_write_sector
#define itoa            potatoes_itoa
#define mallocn         potatoes_mallocn
#define mem_dump        potatoes_mem_dump
#define memcpy          potatoes_memcpy
#define panic           potatoes_panic
#define printf          potatoes_printf
#define printf          potatoes_printf
#define putchar         potatoes_putchar
#define puts            potatoes_puts
#define snprintf        potatoes_snprintf
#define strcat          potatoes_strcat
#define strcmp          potatoes_strcmp
#define strdup          potatoes_strdup
#define strlen          potatoes_strlen
#define strncpy         potatoes_strncpy
#define strsep          potatoes_strsep
#define time2str        potatoes_time2str
#define vsnprintf       potatoes_vsnprintf
